
deployment:
  name: production
  replicaCount: 1
  image:
    app: nginx
    version: latest

service:
  name: production
  type: LoadBalancer
  port: 8080
  targetPort: 8080

  proxy
    enabled: true