
deployment:
  name: helmdeployment
  replicaCount: 1
  image:
    app: nginx
    version: latest

service:
  name: helmservice
  type: LoadBalancer
  port: 80
  targetPort: 80

proxy:
  enabled: false