
deployment: 
  name: prodhelmdeployment
  replicaCount: 3 
  image: 
    app: nginx 
    version: latest 

service: 
  name: prodhelmservice 
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 31234