apiVersion: v1
kind: Service
metadata:
  name: {{ include "myfirstchart.fullname" . }}
  labels:
    app: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx
