# Default values for challenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: apache
  replicaCount: 1
  image:
    app: httpd
    version: 2.4
 
service:
  name: apacheservice
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP

jeremy:
  loadblancerSourceIP: 98.53.204.64/32,98.53.204.65/32,98.53.204.66/32,1.1.1.1/32,2.2.2.2/32,3.3.3.3/32

coando:
  loadblancerSourceIP: 4.4.4.4/32,5.5.5.5/32,6.6.6.6/32,7.7.7.7/32,8.8.8.8/32