# Default values for challenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  image:
    name: challenge
    app: httpd
    version: 2.4
  service:
    type: NodePort
    port: 31234
    name: challengesvc

