# Default values for challenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: challenge 
  image:
    app: nginx
    version: 2.4
service:
  name: chalengesvc
  type: NodePort
  nodePort: 31234 
  port: 80
