apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "challenge.fullname" . }}
  labels:
    app: apache
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          