apiVersion: v1
kind: Service
metadata:
  name: {{ include "challenge.fullname" . }}
  labels:
    app: apache
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: apache
