apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: {{ .Values.coando.loadblancerSourceIP }}
  name: {{ .Values.global.service.name }}
  labels:
   app: apache
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ .Values.global.service.port }}
      targetPort: {{ .Values.global.service.targetPort }}
      name: apache
      protocol: {{ .Values.global.service.protocol }}
  selector:
    app: apache
