apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
   app: apache
spec:
  type: {{ .Values.service.type }}
  loadBalancerSourceRanges: |-
    {{ - range $.Values.loadbalancerSourceIP }}
    - {{ . | title | quote }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: apache
      protocol: {{ .Values.service.protocol }}
  selector:
    app: apache
