apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: 
    {{- range .Values.loadblancerSourceIP  }}
    {{.}}{{- end}}
  name: {{ .Values.service.name }}
  labels:
   app: apache
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: apache
      protocol: {{ .Values.service.protocol }}
  selector:
    app: apache
