---
# Source: myfirstchart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: helmservice
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31234
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx
---
# Source: myfirstchart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxcontainer
          image: "nginx:latest"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
