apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: apache
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      port: 80
  selector:
    app: apache
